import { useState, useEffect, useCallback, useMemo, useRef } from 'react'
import { useTranslation } from 'react-i18next'
import { useVirtualizer } from '@tanstack/react-virtual'
import styles from './DataPreview.module.css'
import { useProjectStore } from '../../store/useProjectStore'
import { highlightJson } from '../../utils/syntaxHighlight'
import { copyToClipboard, downloadJson, downloadCsv } from '../../utils/export'

export default function DataPreview() {
  const { t } = useTranslation()
  const generatedData = useProjectStore((s) => s.generatedData)
  const showToast = useProjectStore((s) => s.showToast)
  const generate = useProjectStore((s) => s.generate)
  const autoGenerated = useRef(false)
  const [viewMode, setViewMode] = useState<'json' | 'table'>('json')

  useEffect(() => {
    if (!autoGenerated.current && !generatedData) {
      autoGenerated.current = true
      generate()
    }
  }, [generatedData, generate])

  const handleCopy = useCallback(async () => {
    if (generatedData) {
      try {
        await copyToClipboard(generatedData)
        showToast(t('dataPreview.copied'))
      } catch {
        showToast(t('dataPreview.copyFailed'))
      }
    }
  }, [generatedData, showToast, t])

  const handleDownloadJson = useCallback(() => {
    if (generatedData) {
      downloadJson(generatedData)
      showToast(t('dataPreview.downloaded'))
    }
  }, [generatedData, showToast, t])

  const handleDownloadCsv = useCallback(() => {
    if (generatedData) {
      downloadCsv(generatedData)
      showToast(t('dataPreview.downloadedCsv'))
    }
  }, [generatedData, showToast, t])

  const isArray = Array.isArray(generatedData)
  const itemCount = isArray ? generatedData.length : 1
  const dataSize = useMemo(() => {
    if (!generatedData) return 0
    const json = JSON.stringify(generatedData)
    return Math.round(json.length / 1024)
  }, [generatedData])

  return (
    <div className="panel-right">
      <div className="card card-preview">
        <div className={styles.previewHeader}>
          <div className={styles.previewMeta}>
            {generatedData ? (
              <span className={styles.metaText}>
                {t('dataPreview.itemCount', { count: itemCount })} · {dataSize} KB
              </span>
            ) : null}
          </div>
          <div className={styles.previewHeaderRight}>
            <div className={styles.previewTabs}>
              <button className={`${styles.previewTab} ${viewMode === 'json' ? styles.previewTabActive : ''}`} onClick={() => setViewMode('json')}>
                {t('dataPreview.json')}
              </button>
              <button className={`${styles.previewTab} ${viewMode === 'table' ? styles.previewTabActive : ''}`} onClick={() => setViewMode('table')} disabled={!isArray}>
                {t('dataPreview.table')}
              </button>
            </div>
            <div className={styles.headerActions}>
              <button className={styles.actionBtn} onClick={handleCopy} title={t('dataPreview.copy')}>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <rect x="9" y="9" width="13" height="13" rx="2" />
                  <path d="M5 15H4a2 2 0 01-2-2V4a2 2 0 012-2h9a2 2 0 012 2v1" />
                </svg>
              </button>
              <button className={styles.actionBtn} onClick={handleDownloadJson} title={t('dataPreview.downloadJson')}>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4" />
                  <polyline points="7 10 12 15 17 10" />
                  <line x1="12" y1="15" x2="12" y2="3" />
                </svg>
              </button>
              <button className={styles.actionBtn} onClick={handleDownloadCsv} title={t('dataPreview.downloadCsv')}>
                <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round">
                  <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" />
                  <polyline points="14 2 14 8 20 8" />
                  <line x1="16" y1="13" x2="8" y2="13" />
                  <line x1="16" y1="17" x2="8" y2="17" />
                </svg>
              </button>
            </div>
          </div>
        </div>
        <div className={styles.previewWrap}>
          {!generatedData ? (
            <div className={styles.emptyState}>
              {t('dataPreview.placeholder')}
            </div>
          ) : viewMode === 'json' ? (
            <JsonPreview data={generatedData} />
          ) : (
            <TablePreview data={generatedData as unknown[]} />
          )}
        </div>
      </div>
    </div>
  )
}

function TablePreview({ data }: { data: unknown[] }) {
  const columns = useMemo(() => {
    const firstRow = data[0]
    if (typeof firstRow === 'object' && firstRow !== null && !Array.isArray(firstRow)) {
      return Object.keys(firstRow)
    }
    return ['value']
  }, [data])

  return (
    <div className={styles.tablePreview}>
      <table>
        <thead>
          <tr>
            {columns.map((col) => (
              <th key={col}>{col}</th>
            ))}
          </tr>
        </thead>
        <tbody>
          {data.slice(0, 1000).map((row, i) => (
            <tr key={i}>
              {columns.map((col) => {
                const val = typeof row === 'object' && row !== null ? (row as Record<string, unknown>)[col] : row
                const display = val === undefined ? '—' : typeof val === 'object' ? JSON.stringify(val) : String(val)
                return (
                  <td key={col} className={val === undefined ? styles.cellEmpty : ''}>
                    {display}
                  </td>
                )
              })}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  )
}

function JsonPreview({ data }: { data: unknown }) {
  const lines = useMemo(() => highlightJson(data), [data])
  const containerRef = useRef<HTMLDivElement>(null)

  // eslint-disable-next-line react-hooks/incompatible-library
  const virtualizer = useVirtualizer({
    count: lines.length,
    getScrollElement: () => containerRef.current,
    estimateSize: () => 22,
    overscan: 20,
  })

  return (
    <div ref={containerRef} className={styles.jsonPreview}>
      <div style={{ height: virtualizer.getTotalSize(), position: 'relative', width: '100%' }}>
        {virtualizer.getVirtualItems().map((vr) => {
          const line = lines[vr.index]
          return (
            <div
              key={vr.key}
              data-index={vr.index}
              ref={virtualizer.measureElement}
              className={styles.jsonLine}
              style={{
                position: 'absolute',
                top: 0,
                left: 0,
                width: '100%',
                transform: `translateY(${vr.start}px)`,
              }}
            >
              <span className={styles.jsonLineNum}>{line.num}</span>
              <span className={styles.jsonContent}>{line.content}</span>
            </div>
          )
        })}
      </div>
    </div>
  )
}